### ISSUE TITLE
Missing element event_date for upcoming stream results in TypeError

### ISSUE THREAD

**Issue by cas--** [add-ons/plugin.video.redbulltv#37]
### Describe the bug ###

Last weekend trying to list the WRC event encountered an error:

`TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

This was due to `element` missing `event_date` attribute (see [pdb_locals])

The quick fix is to fallback with empty string:

```diff
-    list_item.setPath('/notify/' + localize(30024), localize(30025), element.get('event_date') + ' (GMT+' + str(timezone / 3600 * -1))
+    list_item.setPath('/notify/' + localize(30024), localize(30025), element.get('event_date', '') + ' (GMT+' + str(timezone / 3600 * -1))
```

### To Reproduce ###
1. Go to Events -> Upcoming Live Events -> FIA World Rally Championship -> Schedule

### Expected behavior ###

Listing of all scheduled videos for the event, usually one for Friday, Saturday and Sunday.

### Additional context ###

- Operating system: NixOS
- Kodi version: 20
- Addon version: 3.2.2

### Log (if available) ###

```
Error Type: <class 'TypeError'>
Error Contents: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/var/lib/kodi/addons/plugin.video.redbull.tv/resources/lib/addon_entry.py", line 10, in <module>
    run(argv)
  File "/var/lib/kodi/addons/plugin.video.redbull.tv/resources/lib/addon.py", line 221, in run
    plugin.run(params)
  File "/var/lib/kodi/addons/script.module.routing/lib/routing.py", line 130, in run
    self._dispatch(self.path)
  File "/var/lib/kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
    view_func(**kwargs)
  File "/var/lib/kodi/addons/plugin.video.redbull.tv/resources/lib/addon.py", line 120, in browse_collection
    build_menu(redbull.get_collection_url(uid))
  File "/var/lib/kodi/addons/plugin.video.redbull.tv/resources/lib/addon.py", line 165, in build_menu
    list_items.append(generate_list_item(item, PRODUCT))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/kodi/addons/plugin.video.redbull.tv/resources/lib/addon.py", line 194, in generate_list_item
    list_item.setPath('/notify/' + localize(30024), localize(30025), element.get('event_date') + ' (GMT+' + str(timezone / 3600 * -1))
                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

[pdb_locals]: https://github.com/user-attachments/files/17463832/pdb_locals.log

**Comment by cas--** [comment]
I can provide a more comprehensive fix via PR when I get a bit of free time
