### ISSUE TITLE
Returning from empty search gives error

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.redbulltv#4]
### Describe the bug ###
If you go to search, but then return without doing a search query, you get an error.

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <type 'exceptions.TypeError'>
   Error Contents: cannot concatenate 'str' and 'NoneType' objects
   Traceback (most recent call last):
    File "/storage/.kodi/addons/plugin.video.redbulltv/addon_entry.py", line 19, in <module>
      run(argv)
    File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 47, in run
      routing.run(params)
    File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
      self._dispatch(self.path)
    File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
      view_func(**kwargs)
    File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 27, in show_main_menu
      RedBullTV().navigation()
    File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 86, in navigation
       url += kodiutils.get_search_string()
    TypeError: cannot concatenate 'str' and 'NoneType' objects
    -->End of Python script error report<--
```

### To Reproduce ###
1. Go to Search
2. Go back

### Expected behavior ###
Normal main menu

### Additional context ###
- Operating system: LibreELEC v9.2.4
- Kodi version: Kodi v18.8
- Addon version: Red Bull TV v3.1.0
- Using a VPN: yes/no no
- Country you are using the addon from: BE

### Log (if available) ###
```paste below
2020-10-26 01:50:50.515 T:999289728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/addon_entry.py", line 19, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 47, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 27, in show_main_menu
                                                RedBullTV().navigation()
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 86, in navigation
                                                url += kodiutils.get_search_string()
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
2020-10-26 01:50:50.862 T:948953984   ERROR: GetDirectory - Error getting plugin://plugin.video.redbulltv/?api_url=aHR0cHM6Ly9hcGkucmVkYnVsbC50di92My9zZWFyY2g%2fcT0%3d%0a
2020-10-26 01:50:50.866 T:1937566144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.redbulltv/?api_url=aHR0cHM6Ly9hcGkucmVkYnVsbC50di92My9zZWFyY2g%2fcT0%3d%0a) failed
2020-10-26 01:51:10.309 T:999289728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'NoneType' objects
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/addon_entry.py", line 19, in <module>
                                                run(argv)
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 47, in run
                                                routing.run(params)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 27, in show_main_menu
                                                RedBullTV().navigation()
                                              File "/storage/.kodi/addons/plugin.video.redbulltv/resources/lib/addon.py", line 86, in navigation
                                                url += kodiutils.get_search_string()
                                            TypeError: cannot concatenate 'str' and 'NoneType' objects
                                            -->End of Python script error report<--
2020-10-26 01:51:10.683 T:1370485632   ERROR: GetDirectory - Error getting plugin://plugin.video.redbulltv/?api_url=aHR0cHM6Ly9hcGkucmVkYnVsbC50di92My9zZWFyY2g%2fcT0%3d%0a
2020-10-26 01:51:10.687 T:1937566144   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.redbulltv/?api_url=aHR0cHM6Ly9hcGkucmVkYnVsbC50di92My9zZWFyY2g%2fcT0%3d%0a) failed
```

**Comment by piejanssens** [comment]
I'll switch my upstream to my own fork and use PR's going forward ;-)
